/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Return type for `wasmBoot` — pairs the compiled WASM binary with the JS runtime. */
export interface Bootput {
  wasm: Buffer
  runtime: string
}

export declare function wasmBare(source: string): Buffer

export declare function wasmBoot(source: string, imports: string, autoBoot: boolean, minify: boolean): Bootput

export declare function wasmHtml(source: string, imports: string, minify: boolean): string
